common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "dev"
  mlops_api_key: c9356b9c4ce44363bb66366b210201
  mlops_project_name: simulation_2
  mlops_run_name: fedml_torch_fedavg_mnist_lr_1

data_args:
  dataset: "mnist"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn"

train_args:
  federated_optimizer: "decentralized_fl_mod"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 1000
  client_num_participant: 100
  comm_round: 10
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  iteration_number: 20
  topology_neighbors_num_undirected: 10
  topology_neighbors_num_directed: 10
  latency: 0
  b_symmetric: true
  epoch: 5
  time_varying: true
  link_probability: 0.1
  weighted_aggregation: false

simulation_args:
  simulation_end_time: 10000
  simulation_step_time: 1000
  
validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_tracking: false
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false